BUCKETS = ['COUCHBASE', 'MEMCACHED', 'EPHEMERAL']
BUCKETAUTH = ['NONE', 'SASL']
SCENARIOS = ['BasicScenario', 'FailoverScenario', 'RebalanceScenario', 'ServiceFailureScenario']
OPMODES = ['GETTER', 'SETTER', 'ENDURE', 'GETREPLICA', 'INCR', 'DECR']
WORKLOADS = ['KeyValueWorkload']
EPT = ['true', 'False']
SSL = ['true', 'false']
INSTANCES = [1, 10]

FAILOVERACTIONS = ['FO_REBALANCE', 'FO_EJECT', 'FO_EJECT_REBALANCE', 'FO_READD', 'FO_READD_REBALANCE']
FAILOVER_DELAY = 30
REBALANCEMODE = ['IN', 'OUT', 'SWAP']
PROCESSTYPE = ['SYSV_SERVICE', 'MEMCACHED', 'NS_SERVER', 'INDEXER', 'PROJECTOR', 'CBQ_ENGINE', 'RST_CONNECT']
SERVICEACTIONS = ['KILL', 'HANG']
SVCRESTORE_DELAY = 5

